const config = {
    API_URL: process.env.NEXT_PUBLIC_BACKEND_DOMAIN,
    FRONT_DOMAIN: process.env.NEXT_PUBLIC_FRONTEND_DOMAIN,
    POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
    POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    DISTRIBUTION: process.env.NEXT_PUBLIC_DISTRIBUTION,
    STYTCH_TOKEN: process.env.NEXT_PUBLIC_STYTCH_TOKEN
};
  
export default config;
  