const config = {
    API_URL: process.env.NEXT_PUBLIC_BACKEND_DOMAIN,
    WEBAPP_URL: process.env.NEXT_PUBLIC_WEBAPP_DOMAIN,
    MAGIC_LINK_DOMAIN: process.env.NEXT_PUBLIC_MAGIC_LINK_DOMAIN,
    REDIRECT_WEBHOOK_INGRESS: process.env.NEXT_PUBLIC_REDIRECT_WEBHOOK_INGRESS,
    POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
    POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY,
    DISTRIBUTION: process.env.NEXT_PUBLIC_DISTRIBUTION,
};
  
export default config;
  