workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    OpenAPI-Github-Main:
        inputs:
            - location: https://raw.githubusercontent.com/panoratech/Panora/main/packages/api/swagger/swagger-spec.json
        registry:
            location: registry.speakeasyapi.dev/panora/panora/open-api-github-main
targets:
    my-first-target:
        target: typescript
        source: OpenAPI-Github-Main
