/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type AddAtsAttachmentRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original Ats software.
     */
    remoteData?: boolean | undefined;
    unifiedAttachmentInput: components.UnifiedAttachmentInput;
};

export type AddAtsAttachmentResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedAttachmentOutput | undefined;
};

export type AddAtsAttachmentResponse = {
    httpMeta: components.HTTPMetadata;
    object?: AddAtsAttachmentResponseBody | undefined;
    unifiedAttachmentOutput?: components.UnifiedAttachmentOutput | undefined;
};

/** @internal */
export namespace AddAtsAttachmentRequest$ {
    export const inboundSchema: z.ZodType<AddAtsAttachmentRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-connection-token": z.string(),
            remote_data: z.boolean().optional(),
            UnifiedAttachmentInput: components.UnifiedAttachmentInput$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
                UnifiedAttachmentInput: "unifiedAttachmentInput",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        remote_data?: boolean | undefined;
        UnifiedAttachmentInput: components.UnifiedAttachmentInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddAtsAttachmentRequest> = z
        .object({
            xConnectionToken: z.string(),
            remoteData: z.boolean().optional(),
            unifiedAttachmentInput: components.UnifiedAttachmentInput$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
                unifiedAttachmentInput: "UnifiedAttachmentInput",
            });
        });
}

/** @internal */
export namespace AddAtsAttachmentResponseBody$ {
    export const inboundSchema: z.ZodType<AddAtsAttachmentResponseBody, z.ZodTypeDef, unknown> =
        z.object({
            message: z.string().optional(),
            error: z.string().optional(),
            statusCode: z.number(),
            data: components.UnifiedAttachmentOutput$.inboundSchema.optional(),
        });

    export type Outbound = {
        message?: string | undefined;
        error?: string | undefined;
        statusCode: number;
        data?: components.UnifiedAttachmentOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddAtsAttachmentResponseBody> =
        z.object({
            message: z.string().optional(),
            error: z.string().optional(),
            statusCode: z.number(),
            data: components.UnifiedAttachmentOutput$.outboundSchema.optional(),
        });
}

/** @internal */
export namespace AddAtsAttachmentResponse$ {
    export const inboundSchema: z.ZodType<AddAtsAttachmentResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => AddAtsAttachmentResponseBody$.inboundSchema).optional(),
            UnifiedAttachmentOutput: components.UnifiedAttachmentOutput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                UnifiedAttachmentOutput: "unifiedAttachmentOutput",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: AddAtsAttachmentResponseBody$.Outbound | undefined;
        UnifiedAttachmentOutput?: components.UnifiedAttachmentOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddAtsAttachmentResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => AddAtsAttachmentResponseBody$.outboundSchema).optional(),
            unifiedAttachmentOutput: components.UnifiedAttachmentOutput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                unifiedAttachmentOutput: "UnifiedAttachmentOutput",
            });
        });
}
