/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type AddBalanceSheetRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original Accounting software.
     */
    remoteData?: boolean | undefined;
    unifiedBalanceSheetInput: components.UnifiedBalanceSheetInput;
};

export type AddBalanceSheetResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedBalanceSheetOutput | undefined;
};

export type AddBalanceSheetResponse = {
    httpMeta: components.HTTPMetadata;
    object?: AddBalanceSheetResponseBody | undefined;
    unifiedBalanceSheetOutput?: components.UnifiedBalanceSheetOutput | undefined;
};

/** @internal */
export namespace AddBalanceSheetRequest$ {
    export const inboundSchema: z.ZodType<AddBalanceSheetRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-connection-token": z.string(),
            remote_data: z.boolean().optional(),
            UnifiedBalanceSheetInput: components.UnifiedBalanceSheetInput$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
                UnifiedBalanceSheetInput: "unifiedBalanceSheetInput",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        remote_data?: boolean | undefined;
        UnifiedBalanceSheetInput: components.UnifiedBalanceSheetInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddBalanceSheetRequest> = z
        .object({
            xConnectionToken: z.string(),
            remoteData: z.boolean().optional(),
            unifiedBalanceSheetInput: components.UnifiedBalanceSheetInput$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
                unifiedBalanceSheetInput: "UnifiedBalanceSheetInput",
            });
        });
}

/** @internal */
export namespace AddBalanceSheetResponseBody$ {
    export const inboundSchema: z.ZodType<AddBalanceSheetResponseBody, z.ZodTypeDef, unknown> =
        z.object({
            message: z.string().optional(),
            error: z.string().optional(),
            statusCode: z.number(),
            data: components.UnifiedBalanceSheetOutput$.inboundSchema.optional(),
        });

    export type Outbound = {
        message?: string | undefined;
        error?: string | undefined;
        statusCode: number;
        data?: components.UnifiedBalanceSheetOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddBalanceSheetResponseBody> =
        z.object({
            message: z.string().optional(),
            error: z.string().optional(),
            statusCode: z.number(),
            data: components.UnifiedBalanceSheetOutput$.outboundSchema.optional(),
        });
}

/** @internal */
export namespace AddBalanceSheetResponse$ {
    export const inboundSchema: z.ZodType<AddBalanceSheetResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => AddBalanceSheetResponseBody$.inboundSchema).optional(),
            UnifiedBalanceSheetOutput:
                components.UnifiedBalanceSheetOutput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                UnifiedBalanceSheetOutput: "unifiedBalanceSheetOutput",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: AddBalanceSheetResponseBody$.Outbound | undefined;
        UnifiedBalanceSheetOutput?: components.UnifiedBalanceSheetOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddBalanceSheetResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => AddBalanceSheetResponseBody$.outboundSchema).optional(),
            unifiedBalanceSheetOutput:
                components.UnifiedBalanceSheetOutput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                unifiedBalanceSheetOutput: "UnifiedBalanceSheetOutput",
            });
        });
}
