/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type AddDealsRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original Crm software.
     */
    remoteData?: boolean | undefined;
    requestBody: Array<components.UnifiedDealInput>;
};

export type AddDealsResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedDealOutput | undefined;
};

export type AddDealsResponse = {
    httpMeta: components.HTTPMetadata;
    object?: AddDealsResponseBody | undefined;
    unifiedDealOutputs?: Array<components.UnifiedDealOutput> | undefined;
};

/** @internal */
export namespace AddDealsRequest$ {
    export const inboundSchema: z.ZodType<AddDealsRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-connection-token": z.string(),
            remote_data: z.boolean().optional(),
            RequestBody: z.array(components.UnifiedDealInput$.inboundSchema),
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
                RequestBody: "requestBody",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        remote_data?: boolean | undefined;
        RequestBody: Array<components.UnifiedDealInput$.Outbound>;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddDealsRequest> = z
        .object({
            xConnectionToken: z.string(),
            remoteData: z.boolean().optional(),
            requestBody: z.array(components.UnifiedDealInput$.outboundSchema),
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
                requestBody: "RequestBody",
            });
        });
}

/** @internal */
export namespace AddDealsResponseBody$ {
    export const inboundSchema: z.ZodType<AddDealsResponseBody, z.ZodTypeDef, unknown> = z.object({
        message: z.string().optional(),
        error: z.string().optional(),
        statusCode: z.number(),
        data: components.UnifiedDealOutput$.inboundSchema.optional(),
    });

    export type Outbound = {
        message?: string | undefined;
        error?: string | undefined;
        statusCode: number;
        data?: components.UnifiedDealOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddDealsResponseBody> = z.object(
        {
            message: z.string().optional(),
            error: z.string().optional(),
            statusCode: z.number(),
            data: components.UnifiedDealOutput$.outboundSchema.optional(),
        }
    );
}

/** @internal */
export namespace AddDealsResponse$ {
    export const inboundSchema: z.ZodType<AddDealsResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => AddDealsResponseBody$.inboundSchema).optional(),
            UnifiedDealOutputs: z.array(components.UnifiedDealOutput$.inboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                UnifiedDealOutputs: "unifiedDealOutputs",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: AddDealsResponseBody$.Outbound | undefined;
        UnifiedDealOutputs?: Array<components.UnifiedDealOutput$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddDealsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => AddDealsResponseBody$.outboundSchema).optional(),
            unifiedDealOutputs: z.array(components.UnifiedDealOutput$.outboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                unifiedDealOutputs: "UnifiedDealOutputs",
            });
        });
}
