/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type AddEmployeePayrollRunRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original Hris software.
     */
    remoteData?: boolean | undefined;
    unifiedEmployeePayrollRunInput: components.UnifiedEmployeePayrollRunInput;
};

export type AddEmployeePayrollRunResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedEmployeePayrollRunOutput | undefined;
};

export type AddEmployeePayrollRunResponse = {
    httpMeta: components.HTTPMetadata;
    object?: AddEmployeePayrollRunResponseBody | undefined;
    unifiedEmployeePayrollRunOutput?: components.UnifiedEmployeePayrollRunOutput | undefined;
};

/** @internal */
export namespace AddEmployeePayrollRunRequest$ {
    export const inboundSchema: z.ZodType<AddEmployeePayrollRunRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-connection-token": z.string(),
            remote_data: z.boolean().optional(),
            UnifiedEmployeePayrollRunInput:
                components.UnifiedEmployeePayrollRunInput$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
                UnifiedEmployeePayrollRunInput: "unifiedEmployeePayrollRunInput",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        remote_data?: boolean | undefined;
        UnifiedEmployeePayrollRunInput: components.UnifiedEmployeePayrollRunInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddEmployeePayrollRunRequest> = z
        .object({
            xConnectionToken: z.string(),
            remoteData: z.boolean().optional(),
            unifiedEmployeePayrollRunInput:
                components.UnifiedEmployeePayrollRunInput$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
                unifiedEmployeePayrollRunInput: "UnifiedEmployeePayrollRunInput",
            });
        });
}

/** @internal */
export namespace AddEmployeePayrollRunResponseBody$ {
    export const inboundSchema: z.ZodType<
        AddEmployeePayrollRunResponseBody,
        z.ZodTypeDef,
        unknown
    > = z.object({
        message: z.string().optional(),
        error: z.string().optional(),
        statusCode: z.number(),
        data: components.UnifiedEmployeePayrollRunOutput$.inboundSchema.optional(),
    });

    export type Outbound = {
        message?: string | undefined;
        error?: string | undefined;
        statusCode: number;
        data?: components.UnifiedEmployeePayrollRunOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        AddEmployeePayrollRunResponseBody
    > = z.object({
        message: z.string().optional(),
        error: z.string().optional(),
        statusCode: z.number(),
        data: components.UnifiedEmployeePayrollRunOutput$.outboundSchema.optional(),
    });
}

/** @internal */
export namespace AddEmployeePayrollRunResponse$ {
    export const inboundSchema: z.ZodType<AddEmployeePayrollRunResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => AddEmployeePayrollRunResponseBody$.inboundSchema).optional(),
            UnifiedEmployeePayrollRunOutput:
                components.UnifiedEmployeePayrollRunOutput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                UnifiedEmployeePayrollRunOutput: "unifiedEmployeePayrollRunOutput",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: AddEmployeePayrollRunResponseBody$.Outbound | undefined;
        UnifiedEmployeePayrollRunOutput?:
            | components.UnifiedEmployeePayrollRunOutput$.Outbound
            | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddEmployeePayrollRunResponse> =
        z
            .object({
                httpMeta: components.HTTPMetadata$.outboundSchema,
                object: z.lazy(() => AddEmployeePayrollRunResponseBody$.outboundSchema).optional(),
                unifiedEmployeePayrollRunOutput:
                    components.UnifiedEmployeePayrollRunOutput$.outboundSchema.optional(),
            })
            .transform((v) => {
                return remap$(v, {
                    httpMeta: "HttpMeta",
                    unifiedEmployeePayrollRunOutput: "UnifiedEmployeePayrollRunOutput",
                });
            });
}
