/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type AddOfficeRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original Ats software.
     */
    remoteData?: boolean | undefined;
    unifiedOfficeInput: components.UnifiedOfficeInput;
};

export type AddOfficeResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedOfficeOutput | undefined;
};

export type AddOfficeResponse = {
    httpMeta: components.HTTPMetadata;
    object?: AddOfficeResponseBody | undefined;
    unifiedOfficeOutput?: components.UnifiedOfficeOutput | undefined;
};

/** @internal */
export namespace AddOfficeRequest$ {
    export const inboundSchema: z.ZodType<AddOfficeRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-connection-token": z.string(),
            remote_data: z.boolean().optional(),
            UnifiedOfficeInput: components.UnifiedOfficeInput$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
                UnifiedOfficeInput: "unifiedOfficeInput",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        remote_data?: boolean | undefined;
        UnifiedOfficeInput: components.UnifiedOfficeInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddOfficeRequest> = z
        .object({
            xConnectionToken: z.string(),
            remoteData: z.boolean().optional(),
            unifiedOfficeInput: components.UnifiedOfficeInput$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
                unifiedOfficeInput: "UnifiedOfficeInput",
            });
        });
}

/** @internal */
export namespace AddOfficeResponseBody$ {
    export const inboundSchema: z.ZodType<AddOfficeResponseBody, z.ZodTypeDef, unknown> = z.object({
        message: z.string().optional(),
        error: z.string().optional(),
        statusCode: z.number(),
        data: components.UnifiedOfficeOutput$.inboundSchema.optional(),
    });

    export type Outbound = {
        message?: string | undefined;
        error?: string | undefined;
        statusCode: number;
        data?: components.UnifiedOfficeOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddOfficeResponseBody> =
        z.object({
            message: z.string().optional(),
            error: z.string().optional(),
            statusCode: z.number(),
            data: components.UnifiedOfficeOutput$.outboundSchema.optional(),
        });
}

/** @internal */
export namespace AddOfficeResponse$ {
    export const inboundSchema: z.ZodType<AddOfficeResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => AddOfficeResponseBody$.inboundSchema).optional(),
            UnifiedOfficeOutput: components.UnifiedOfficeOutput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                UnifiedOfficeOutput: "unifiedOfficeOutput",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: AddOfficeResponseBody$.Outbound | undefined;
        UnifiedOfficeOutput?: components.UnifiedOfficeOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddOfficeResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => AddOfficeResponseBody$.outboundSchema).optional(),
            unifiedOfficeOutput: components.UnifiedOfficeOutput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                unifiedOfficeOutput: "UnifiedOfficeOutput",
            });
        });
}
