/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type AddPhoneNumberRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original Accounting software.
     */
    remoteData?: boolean | undefined;
    unifiedPhoneNumberInput: components.UnifiedPhoneNumberInput;
};

export type AddPhoneNumberResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedPhoneNumberOutput | undefined;
};

export type AddPhoneNumberResponse = {
    httpMeta: components.HTTPMetadata;
    object?: AddPhoneNumberResponseBody | undefined;
    unifiedPhoneNumberOutput?: components.UnifiedPhoneNumberOutput | undefined;
};

/** @internal */
export namespace AddPhoneNumberRequest$ {
    export const inboundSchema: z.ZodType<AddPhoneNumberRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-connection-token": z.string(),
            remote_data: z.boolean().optional(),
            UnifiedPhoneNumberInput: components.UnifiedPhoneNumberInput$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
                UnifiedPhoneNumberInput: "unifiedPhoneNumberInput",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        remote_data?: boolean | undefined;
        UnifiedPhoneNumberInput: components.UnifiedPhoneNumberInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddPhoneNumberRequest> = z
        .object({
            xConnectionToken: z.string(),
            remoteData: z.boolean().optional(),
            unifiedPhoneNumberInput: components.UnifiedPhoneNumberInput$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
                unifiedPhoneNumberInput: "UnifiedPhoneNumberInput",
            });
        });
}

/** @internal */
export namespace AddPhoneNumberResponseBody$ {
    export const inboundSchema: z.ZodType<AddPhoneNumberResponseBody, z.ZodTypeDef, unknown> =
        z.object({
            message: z.string().optional(),
            error: z.string().optional(),
            statusCode: z.number(),
            data: components.UnifiedPhoneNumberOutput$.inboundSchema.optional(),
        });

    export type Outbound = {
        message?: string | undefined;
        error?: string | undefined;
        statusCode: number;
        data?: components.UnifiedPhoneNumberOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddPhoneNumberResponseBody> =
        z.object({
            message: z.string().optional(),
            error: z.string().optional(),
            statusCode: z.number(),
            data: components.UnifiedPhoneNumberOutput$.outboundSchema.optional(),
        });
}

/** @internal */
export namespace AddPhoneNumberResponse$ {
    export const inboundSchema: z.ZodType<AddPhoneNumberResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => AddPhoneNumberResponseBody$.inboundSchema).optional(),
            UnifiedPhoneNumberOutput: components.UnifiedPhoneNumberOutput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                UnifiedPhoneNumberOutput: "unifiedPhoneNumberOutput",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: AddPhoneNumberResponseBody$.Outbound | undefined;
        UnifiedPhoneNumberOutput?: components.UnifiedPhoneNumberOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddPhoneNumberResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => AddPhoneNumberResponseBody$.outboundSchema).optional(),
            unifiedPhoneNumberOutput:
                components.UnifiedPhoneNumberOutput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                unifiedPhoneNumberOutput: "UnifiedPhoneNumberOutput",
            });
        });
}
