/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type AddTemplateRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original Marketingautomation software.
     */
    remoteData?: boolean | undefined;
    unifiedTemplateInput: components.UnifiedTemplateInput;
};

export type AddTemplateResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedTemplateOutput | undefined;
};

export type AddTemplateResponse = components.UnifiedTemplateOutput | AddTemplateResponseBody;

/** @internal */
export namespace AddTemplateRequest$ {
    export const inboundSchema: z.ZodType<AddTemplateRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-connection-token": z.string(),
            remote_data: z.boolean().optional(),
            UnifiedTemplateInput: components.UnifiedTemplateInput$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
                UnifiedTemplateInput: "unifiedTemplateInput",
            });
        });

    export type Outbound = {
        "x-connection-token": string;
        remote_data?: boolean | undefined;
        UnifiedTemplateInput: components.UnifiedTemplateInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddTemplateRequest> = z
        .object({
            xConnectionToken: z.string(),
            remoteData: z.boolean().optional(),
            unifiedTemplateInput: components.UnifiedTemplateInput$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                xConnectionToken: "x-connection-token",
                remoteData: "remote_data",
                unifiedTemplateInput: "UnifiedTemplateInput",
            });
        });
}

/** @internal */
export namespace AddTemplateResponseBody$ {
    export const inboundSchema: z.ZodType<AddTemplateResponseBody, z.ZodTypeDef, unknown> =
        z.object({
            message: z.string().optional(),
            error: z.string().optional(),
            statusCode: z.number(),
            data: components.UnifiedTemplateOutput$.inboundSchema.optional(),
        });

    export type Outbound = {
        message?: string | undefined;
        error?: string | undefined;
        statusCode: number;
        data?: components.UnifiedTemplateOutput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddTemplateResponseBody> =
        z.object({
            message: z.string().optional(),
            error: z.string().optional(),
            statusCode: z.number(),
            data: components.UnifiedTemplateOutput$.outboundSchema.optional(),
        });
}

/** @internal */
export namespace AddTemplateResponse$ {
    export const inboundSchema: z.ZodType<AddTemplateResponse, z.ZodTypeDef, unknown> = z.union([
        components.UnifiedTemplateOutput$.inboundSchema,
        z.lazy(() => AddTemplateResponseBody$.inboundSchema),
    ]);

    export type Outbound =
        | components.UnifiedTemplateOutput$.Outbound
        | AddTemplateResponseBody$.Outbound;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddTemplateResponse> = z.union([
        components.UnifiedTemplateOutput$.outboundSchema,
        z.lazy(() => AddTemplateResponseBody$.outboundSchema),
    ]);
}
