/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type AddTimeoffRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original Hris software.
     */
    remoteData?: boolean | undefined;
    unifiedTimeoffInput: components.UnifiedTimeoffInput;
};

export type AddTimeoffResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedTimeoffOutput | undefined;
};

export type AddTimeoffResponse = components.UnifiedTimeoffOutput | AddTimeoffResponseBody;

/** @internal */
export const AddTimeoffRequest$inboundSchema: z.ZodType<AddTimeoffRequest, z.ZodTypeDef, unknown> =
    z
        .object({
            "x-connection-token": z.string(),
            remote_data: z.boolean().optional(),
            UnifiedTimeoffInput: components.UnifiedTimeoffInput$inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                "x-connection-token": "xConnectionToken",
                remote_data: "remoteData",
                UnifiedTimeoffInput: "unifiedTimeoffInput",
            });
        });

/** @internal */
export type AddTimeoffRequest$Outbound = {
    "x-connection-token": string;
    remote_data?: boolean | undefined;
    UnifiedTimeoffInput: components.UnifiedTimeoffInput$Outbound;
};

/** @internal */
export const AddTimeoffRequest$outboundSchema: z.ZodType<
    AddTimeoffRequest$Outbound,
    z.ZodTypeDef,
    AddTimeoffRequest
> = z
    .object({
        xConnectionToken: z.string(),
        remoteData: z.boolean().optional(),
        unifiedTimeoffInput: components.UnifiedTimeoffInput$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            xConnectionToken: "x-connection-token",
            remoteData: "remote_data",
            unifiedTimeoffInput: "UnifiedTimeoffInput",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddTimeoffRequest$ {
    /** @deprecated use `AddTimeoffRequest$inboundSchema` instead. */
    export const inboundSchema = AddTimeoffRequest$inboundSchema;
    /** @deprecated use `AddTimeoffRequest$outboundSchema` instead. */
    export const outboundSchema = AddTimeoffRequest$outboundSchema;
    /** @deprecated use `AddTimeoffRequest$Outbound` instead. */
    export type Outbound = AddTimeoffRequest$Outbound;
}

/** @internal */
export const AddTimeoffResponseBody$inboundSchema: z.ZodType<
    AddTimeoffResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedTimeoffOutput$inboundSchema.optional(),
});

/** @internal */
export type AddTimeoffResponseBody$Outbound = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedTimeoffOutput$Outbound | undefined;
};

/** @internal */
export const AddTimeoffResponseBody$outboundSchema: z.ZodType<
    AddTimeoffResponseBody$Outbound,
    z.ZodTypeDef,
    AddTimeoffResponseBody
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedTimeoffOutput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddTimeoffResponseBody$ {
    /** @deprecated use `AddTimeoffResponseBody$inboundSchema` instead. */
    export const inboundSchema = AddTimeoffResponseBody$inboundSchema;
    /** @deprecated use `AddTimeoffResponseBody$outboundSchema` instead. */
    export const outboundSchema = AddTimeoffResponseBody$outboundSchema;
    /** @deprecated use `AddTimeoffResponseBody$Outbound` instead. */
    export type Outbound = AddTimeoffResponseBody$Outbound;
}

/** @internal */
export const AddTimeoffResponse$inboundSchema: z.ZodType<
    AddTimeoffResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    components.UnifiedTimeoffOutput$inboundSchema,
    z.lazy(() => AddTimeoffResponseBody$inboundSchema),
]);

/** @internal */
export type AddTimeoffResponse$Outbound =
    | components.UnifiedTimeoffOutput$Outbound
    | AddTimeoffResponseBody$Outbound;

/** @internal */
export const AddTimeoffResponse$outboundSchema: z.ZodType<
    AddTimeoffResponse$Outbound,
    z.ZodTypeDef,
    AddTimeoffResponse
> = z.union([
    components.UnifiedTimeoffOutput$outboundSchema,
    z.lazy(() => AddTimeoffResponseBody$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddTimeoffResponse$ {
    /** @deprecated use `AddTimeoffResponse$inboundSchema` instead. */
    export const inboundSchema = AddTimeoffResponse$inboundSchema;
    /** @deprecated use `AddTimeoffResponse$outboundSchema` instead. */
    export const outboundSchema = AddTimeoffResponse$outboundSchema;
    /** @deprecated use `AddTimeoffResponse$Outbound` instead. */
    export type Outbound = AddTimeoffResponse$Outbound;
}
