/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetBalanceSheetRequest = {
    /**
     * id of the balancesheet you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Accounting software.
     */
    remoteData?: boolean | undefined;
};

export type GetBalanceSheetResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedBalanceSheetOutput | undefined;
};

/** @internal */
export const GetBalanceSheetRequest$inboundSchema: z.ZodType<
    GetBalanceSheetRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        remote_data: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remote_data: "remoteData",
        });
    });

/** @internal */
export type GetBalanceSheetRequest$Outbound = {
    id: string;
    remote_data?: boolean | undefined;
};

/** @internal */
export const GetBalanceSheetRequest$outboundSchema: z.ZodType<
    GetBalanceSheetRequest$Outbound,
    z.ZodTypeDef,
    GetBalanceSheetRequest
> = z
    .object({
        id: z.string(),
        remoteData: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBalanceSheetRequest$ {
    /** @deprecated use `GetBalanceSheetRequest$inboundSchema` instead. */
    export const inboundSchema = GetBalanceSheetRequest$inboundSchema;
    /** @deprecated use `GetBalanceSheetRequest$outboundSchema` instead. */
    export const outboundSchema = GetBalanceSheetRequest$outboundSchema;
    /** @deprecated use `GetBalanceSheetRequest$Outbound` instead. */
    export type Outbound = GetBalanceSheetRequest$Outbound;
}

/** @internal */
export const GetBalanceSheetResponseBody$inboundSchema: z.ZodType<
    GetBalanceSheetResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedBalanceSheetOutput$inboundSchema.optional(),
});

/** @internal */
export type GetBalanceSheetResponseBody$Outbound = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedBalanceSheetOutput$Outbound | undefined;
};

/** @internal */
export const GetBalanceSheetResponseBody$outboundSchema: z.ZodType<
    GetBalanceSheetResponseBody$Outbound,
    z.ZodTypeDef,
    GetBalanceSheetResponseBody
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedBalanceSheetOutput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBalanceSheetResponseBody$ {
    /** @deprecated use `GetBalanceSheetResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetBalanceSheetResponseBody$inboundSchema;
    /** @deprecated use `GetBalanceSheetResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetBalanceSheetResponseBody$outboundSchema;
    /** @deprecated use `GetBalanceSheetResponseBody$Outbound` instead. */
    export type Outbound = GetBalanceSheetResponseBody$Outbound;
}
