/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetCompaniesRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original software.
     */
    remoteData?: boolean | undefined;
    /**
     * Set to get the number of records.
     */
    limit?: number | undefined;
    /**
     * Set to get the number of records after this cursor.
     */
    cursor?: string | undefined;
};

export type GetCompaniesResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedCompanyOutput | undefined;
};

/** @internal */
export const GetCompaniesRequest$inboundSchema: z.ZodType<
    GetCompaniesRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        "x-connection-token": z.string(),
        remote_data: z.boolean().optional(),
        limit: z.number().default(50),
        cursor: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-connection-token": "xConnectionToken",
            remote_data: "remoteData",
        });
    });

/** @internal */
export type GetCompaniesRequest$Outbound = {
    "x-connection-token": string;
    remote_data?: boolean | undefined;
    limit: number;
    cursor?: string | undefined;
};

/** @internal */
export const GetCompaniesRequest$outboundSchema: z.ZodType<
    GetCompaniesRequest$Outbound,
    z.ZodTypeDef,
    GetCompaniesRequest
> = z
    .object({
        xConnectionToken: z.string(),
        remoteData: z.boolean().optional(),
        limit: z.number().default(50),
        cursor: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xConnectionToken: "x-connection-token",
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCompaniesRequest$ {
    /** @deprecated use `GetCompaniesRequest$inboundSchema` instead. */
    export const inboundSchema = GetCompaniesRequest$inboundSchema;
    /** @deprecated use `GetCompaniesRequest$outboundSchema` instead. */
    export const outboundSchema = GetCompaniesRequest$outboundSchema;
    /** @deprecated use `GetCompaniesRequest$Outbound` instead. */
    export type Outbound = GetCompaniesRequest$Outbound;
}

/** @internal */
export const GetCompaniesResponseBody$inboundSchema: z.ZodType<
    GetCompaniesResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedCompanyOutput$inboundSchema.optional(),
});

/** @internal */
export type GetCompaniesResponseBody$Outbound = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedCompanyOutput$Outbound | undefined;
};

/** @internal */
export const GetCompaniesResponseBody$outboundSchema: z.ZodType<
    GetCompaniesResponseBody$Outbound,
    z.ZodTypeDef,
    GetCompaniesResponseBody
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedCompanyOutput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCompaniesResponseBody$ {
    /** @deprecated use `GetCompaniesResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetCompaniesResponseBody$inboundSchema;
    /** @deprecated use `GetCompaniesResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetCompaniesResponseBody$outboundSchema;
    /** @deprecated use `GetCompaniesResponseBody$Outbound` instead. */
    export type Outbound = GetCompaniesResponseBody$Outbound;
}
