/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetCashflowStatementRequest = {
    /**
     * id of the cashflowstatement you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Accounting software.
     */
    remoteData?: boolean | undefined;
};

export type GetCashflowStatementResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedCashflowStatementOutput | undefined;
};

/** @internal */
export const GetCashflowStatementRequest$inboundSchema: z.ZodType<
    GetCashflowStatementRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        remote_data: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remote_data: "remoteData",
        });
    });

/** @internal */
export type GetCashflowStatementRequest$Outbound = {
    id: string;
    remote_data?: boolean | undefined;
};

/** @internal */
export const GetCashflowStatementRequest$outboundSchema: z.ZodType<
    GetCashflowStatementRequest$Outbound,
    z.ZodTypeDef,
    GetCashflowStatementRequest
> = z
    .object({
        id: z.string(),
        remoteData: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCashflowStatementRequest$ {
    /** @deprecated use `GetCashflowStatementRequest$inboundSchema` instead. */
    export const inboundSchema = GetCashflowStatementRequest$inboundSchema;
    /** @deprecated use `GetCashflowStatementRequest$outboundSchema` instead. */
    export const outboundSchema = GetCashflowStatementRequest$outboundSchema;
    /** @deprecated use `GetCashflowStatementRequest$Outbound` instead. */
    export type Outbound = GetCashflowStatementRequest$Outbound;
}

/** @internal */
export const GetCashflowStatementResponseBody$inboundSchema: z.ZodType<
    GetCashflowStatementResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedCashflowStatementOutput$inboundSchema.optional(),
});

/** @internal */
export type GetCashflowStatementResponseBody$Outbound = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedCashflowStatementOutput$Outbound | undefined;
};

/** @internal */
export const GetCashflowStatementResponseBody$outboundSchema: z.ZodType<
    GetCashflowStatementResponseBody$Outbound,
    z.ZodTypeDef,
    GetCashflowStatementResponseBody
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedCashflowStatementOutput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCashflowStatementResponseBody$ {
    /** @deprecated use `GetCashflowStatementResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetCashflowStatementResponseBody$inboundSchema;
    /** @deprecated use `GetCashflowStatementResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetCashflowStatementResponseBody$outboundSchema;
    /** @deprecated use `GetCashflowStatementResponseBody$Outbound` instead. */
    export type Outbound = GetCashflowStatementResponseBody$Outbound;
}
