/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetEmailsRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original Marketingautomation software.
     */
    remoteData?: boolean | undefined;
};

export type GetEmailsResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedEmailOutput | undefined;
};

/** @internal */
export const GetEmailsRequest$inboundSchema: z.ZodType<GetEmailsRequest, z.ZodTypeDef, unknown> = z
    .object({
        "x-connection-token": z.string(),
        remote_data: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-connection-token": "xConnectionToken",
            remote_data: "remoteData",
        });
    });

/** @internal */
export type GetEmailsRequest$Outbound = {
    "x-connection-token": string;
    remote_data?: boolean | undefined;
};

/** @internal */
export const GetEmailsRequest$outboundSchema: z.ZodType<
    GetEmailsRequest$Outbound,
    z.ZodTypeDef,
    GetEmailsRequest
> = z
    .object({
        xConnectionToken: z.string(),
        remoteData: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xConnectionToken: "x-connection-token",
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetEmailsRequest$ {
    /** @deprecated use `GetEmailsRequest$inboundSchema` instead. */
    export const inboundSchema = GetEmailsRequest$inboundSchema;
    /** @deprecated use `GetEmailsRequest$outboundSchema` instead. */
    export const outboundSchema = GetEmailsRequest$outboundSchema;
    /** @deprecated use `GetEmailsRequest$Outbound` instead. */
    export type Outbound = GetEmailsRequest$Outbound;
}

/** @internal */
export const GetEmailsResponseBody$inboundSchema: z.ZodType<
    GetEmailsResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedEmailOutput$inboundSchema.optional(),
});

/** @internal */
export type GetEmailsResponseBody$Outbound = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedEmailOutput$Outbound | undefined;
};

/** @internal */
export const GetEmailsResponseBody$outboundSchema: z.ZodType<
    GetEmailsResponseBody$Outbound,
    z.ZodTypeDef,
    GetEmailsResponseBody
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedEmailOutput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetEmailsResponseBody$ {
    /** @deprecated use `GetEmailsResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetEmailsResponseBody$inboundSchema;
    /** @deprecated use `GetEmailsResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetEmailsResponseBody$outboundSchema;
    /** @deprecated use `GetEmailsResponseBody$Outbound` instead. */
    export type Outbound = GetEmailsResponseBody$Outbound;
}
