/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetHrisCompanyRequest = {
    /**
     * id of the company you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Hris software.
     */
    remoteData?: boolean | undefined;
};

export type GetHrisCompanyResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedCompanyOutput | undefined;
};

/** @internal */
export const GetHrisCompanyRequest$inboundSchema: z.ZodType<
    GetHrisCompanyRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        remote_data: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remote_data: "remoteData",
        });
    });

/** @internal */
export type GetHrisCompanyRequest$Outbound = {
    id: string;
    remote_data?: boolean | undefined;
};

/** @internal */
export const GetHrisCompanyRequest$outboundSchema: z.ZodType<
    GetHrisCompanyRequest$Outbound,
    z.ZodTypeDef,
    GetHrisCompanyRequest
> = z
    .object({
        id: z.string(),
        remoteData: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHrisCompanyRequest$ {
    /** @deprecated use `GetHrisCompanyRequest$inboundSchema` instead. */
    export const inboundSchema = GetHrisCompanyRequest$inboundSchema;
    /** @deprecated use `GetHrisCompanyRequest$outboundSchema` instead. */
    export const outboundSchema = GetHrisCompanyRequest$outboundSchema;
    /** @deprecated use `GetHrisCompanyRequest$Outbound` instead. */
    export type Outbound = GetHrisCompanyRequest$Outbound;
}

/** @internal */
export const GetHrisCompanyResponseBody$inboundSchema: z.ZodType<
    GetHrisCompanyResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedCompanyOutput$inboundSchema.optional(),
});

/** @internal */
export type GetHrisCompanyResponseBody$Outbound = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedCompanyOutput$Outbound | undefined;
};

/** @internal */
export const GetHrisCompanyResponseBody$outboundSchema: z.ZodType<
    GetHrisCompanyResponseBody$Outbound,
    z.ZodTypeDef,
    GetHrisCompanyResponseBody
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedCompanyOutput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHrisCompanyResponseBody$ {
    /** @deprecated use `GetHrisCompanyResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetHrisCompanyResponseBody$inboundSchema;
    /** @deprecated use `GetHrisCompanyResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetHrisCompanyResponseBody$outboundSchema;
    /** @deprecated use `GetHrisCompanyResponseBody$Outbound` instead. */
    export type Outbound = GetHrisCompanyResponseBody$Outbound;
}
