/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetItemsRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original Accounting software.
     */
    remoteData?: boolean | undefined;
};

export type GetItemsResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedItemOutput | undefined;
};

/** @internal */
export const GetItemsRequest$inboundSchema: z.ZodType<GetItemsRequest, z.ZodTypeDef, unknown> = z
    .object({
        "x-connection-token": z.string(),
        remote_data: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-connection-token": "xConnectionToken",
            remote_data: "remoteData",
        });
    });

/** @internal */
export type GetItemsRequest$Outbound = {
    "x-connection-token": string;
    remote_data?: boolean | undefined;
};

/** @internal */
export const GetItemsRequest$outboundSchema: z.ZodType<
    GetItemsRequest$Outbound,
    z.ZodTypeDef,
    GetItemsRequest
> = z
    .object({
        xConnectionToken: z.string(),
        remoteData: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xConnectionToken: "x-connection-token",
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetItemsRequest$ {
    /** @deprecated use `GetItemsRequest$inboundSchema` instead. */
    export const inboundSchema = GetItemsRequest$inboundSchema;
    /** @deprecated use `GetItemsRequest$outboundSchema` instead. */
    export const outboundSchema = GetItemsRequest$outboundSchema;
    /** @deprecated use `GetItemsRequest$Outbound` instead. */
    export type Outbound = GetItemsRequest$Outbound;
}

/** @internal */
export const GetItemsResponseBody$inboundSchema: z.ZodType<
    GetItemsResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedItemOutput$inboundSchema.optional(),
});

/** @internal */
export type GetItemsResponseBody$Outbound = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedItemOutput$Outbound | undefined;
};

/** @internal */
export const GetItemsResponseBody$outboundSchema: z.ZodType<
    GetItemsResponseBody$Outbound,
    z.ZodTypeDef,
    GetItemsResponseBody
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedItemOutput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetItemsResponseBody$ {
    /** @deprecated use `GetItemsResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetItemsResponseBody$inboundSchema;
    /** @deprecated use `GetItemsResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetItemsResponseBody$outboundSchema;
    /** @deprecated use `GetItemsResponseBody$Outbound` instead. */
    export type Outbound = GetItemsResponseBody$Outbound;
}
