/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetLocationRequest = {
    /**
     * id of the location you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Hris software.
     */
    remoteData?: boolean | undefined;
};

export type GetLocationResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedLocationOutput | undefined;
};

/** @internal */
export const GetLocationRequest$inboundSchema: z.ZodType<
    GetLocationRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        remote_data: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remote_data: "remoteData",
        });
    });

/** @internal */
export type GetLocationRequest$Outbound = {
    id: string;
    remote_data?: boolean | undefined;
};

/** @internal */
export const GetLocationRequest$outboundSchema: z.ZodType<
    GetLocationRequest$Outbound,
    z.ZodTypeDef,
    GetLocationRequest
> = z
    .object({
        id: z.string(),
        remoteData: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetLocationRequest$ {
    /** @deprecated use `GetLocationRequest$inboundSchema` instead. */
    export const inboundSchema = GetLocationRequest$inboundSchema;
    /** @deprecated use `GetLocationRequest$outboundSchema` instead. */
    export const outboundSchema = GetLocationRequest$outboundSchema;
    /** @deprecated use `GetLocationRequest$Outbound` instead. */
    export type Outbound = GetLocationRequest$Outbound;
}

/** @internal */
export const GetLocationResponseBody$inboundSchema: z.ZodType<
    GetLocationResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedLocationOutput$inboundSchema.optional(),
});

/** @internal */
export type GetLocationResponseBody$Outbound = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedLocationOutput$Outbound | undefined;
};

/** @internal */
export const GetLocationResponseBody$outboundSchema: z.ZodType<
    GetLocationResponseBody$Outbound,
    z.ZodTypeDef,
    GetLocationResponseBody
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedLocationOutput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetLocationResponseBody$ {
    /** @deprecated use `GetLocationResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetLocationResponseBody$inboundSchema;
    /** @deprecated use `GetLocationResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetLocationResponseBody$outboundSchema;
    /** @deprecated use `GetLocationResponseBody$Outbound` instead. */
    export type Outbound = GetLocationResponseBody$Outbound;
}
