/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetLinkedUserRequest = {
    id: string;
};

export type GetLinkedUserResponse = {
    httpMeta: components.HTTPMetadata;
};

/** @internal */
export namespace GetLinkedUserRequest$ {
    export const inboundSchema: z.ZodType<GetLinkedUserRequest, z.ZodTypeDef, unknown> = z.object({
        id: z.string(),
    });

    export type Outbound = {
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLinkedUserRequest> = z.object(
        {
            id: z.string(),
        }
    );
}

/** @internal */
export namespace GetLinkedUserResponse$ {
    export const inboundSchema: z.ZodType<GetLinkedUserResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetLinkedUserResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
            });
        });
}
