/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type GetManagedWebhooksRequest = {
    idConnection: string;
};

/** @internal */
export const GetManagedWebhooksRequest$inboundSchema: z.ZodType<
    GetManagedWebhooksRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id_connection: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            id_connection: "idConnection",
        });
    });

/** @internal */
export type GetManagedWebhooksRequest$Outbound = {
    id_connection: string;
};

/** @internal */
export const GetManagedWebhooksRequest$outboundSchema: z.ZodType<
    GetManagedWebhooksRequest$Outbound,
    z.ZodTypeDef,
    GetManagedWebhooksRequest
> = z
    .object({
        idConnection: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            idConnection: "id_connection",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetManagedWebhooksRequest$ {
    /** @deprecated use `GetManagedWebhooksRequest$inboundSchema` instead. */
    export const inboundSchema = GetManagedWebhooksRequest$inboundSchema;
    /** @deprecated use `GetManagedWebhooksRequest$outboundSchema` instead. */
    export const outboundSchema = GetManagedWebhooksRequest$outboundSchema;
    /** @deprecated use `GetManagedWebhooksRequest$Outbound` instead. */
    export type Outbound = GetManagedWebhooksRequest$Outbound;
}
