/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type GetManagedWebhooksRequest = {
    idConnection: string;
};

export type GetManagedWebhooksResponse = {
    httpMeta: components.HTTPMetadata;
};

/** @internal */
export namespace GetManagedWebhooksRequest$ {
    export const inboundSchema: z.ZodType<GetManagedWebhooksRequest, z.ZodTypeDef, unknown> = z
        .object({
            id_connection: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                id_connection: "idConnection",
            });
        });

    export type Outbound = {
        id_connection: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetManagedWebhooksRequest> = z
        .object({
            idConnection: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                idConnection: "id_connection",
            });
        });
}

/** @internal */
export namespace GetManagedWebhooksResponse$ {
    export const inboundSchema: z.ZodType<GetManagedWebhooksResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetManagedWebhooksResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
            });
        });
}
