/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetNotesRequest = {
    /**
     * The connection token
     */
    xConnectionToken: string;
    /**
     * Set to true to include data from the original software.
     */
    remoteData?: boolean | undefined;
    /**
     * Set to get the number of records.
     */
    limit?: number | undefined;
    /**
     * Set to get the number of records after this cursor.
     */
    cursor?: string | undefined;
};

export type GetNotesResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedNoteOutput | undefined;
};

/** @internal */
export const GetNotesRequest$inboundSchema: z.ZodType<GetNotesRequest, z.ZodTypeDef, unknown> = z
    .object({
        "x-connection-token": z.string(),
        remote_data: z.boolean().optional(),
        limit: z.number().default(50),
        cursor: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-connection-token": "xConnectionToken",
            remote_data: "remoteData",
        });
    });

/** @internal */
export type GetNotesRequest$Outbound = {
    "x-connection-token": string;
    remote_data?: boolean | undefined;
    limit: number;
    cursor?: string | undefined;
};

/** @internal */
export const GetNotesRequest$outboundSchema: z.ZodType<
    GetNotesRequest$Outbound,
    z.ZodTypeDef,
    GetNotesRequest
> = z
    .object({
        xConnectionToken: z.string(),
        remoteData: z.boolean().optional(),
        limit: z.number().default(50),
        cursor: z.string().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xConnectionToken: "x-connection-token",
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetNotesRequest$ {
    /** @deprecated use `GetNotesRequest$inboundSchema` instead. */
    export const inboundSchema = GetNotesRequest$inboundSchema;
    /** @deprecated use `GetNotesRequest$outboundSchema` instead. */
    export const outboundSchema = GetNotesRequest$outboundSchema;
    /** @deprecated use `GetNotesRequest$Outbound` instead. */
    export type Outbound = GetNotesRequest$Outbound;
}

/** @internal */
export const GetNotesResponseBody$inboundSchema: z.ZodType<
    GetNotesResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedNoteOutput$inboundSchema.optional(),
});

/** @internal */
export type GetNotesResponseBody$Outbound = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedNoteOutput$Outbound | undefined;
};

/** @internal */
export const GetNotesResponseBody$outboundSchema: z.ZodType<
    GetNotesResponseBody$Outbound,
    z.ZodTypeDef,
    GetNotesResponseBody
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedNoteOutput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetNotesResponseBody$ {
    /** @deprecated use `GetNotesResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetNotesResponseBody$inboundSchema;
    /** @deprecated use `GetNotesResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetNotesResponseBody$outboundSchema;
    /** @deprecated use `GetNotesResponseBody$Outbound` instead. */
    export type Outbound = GetNotesResponseBody$Outbound;
}
