/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetOfficeRequest = {
    /**
     * id of the office you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Ats software.
     */
    remoteData?: boolean | undefined;
};

export type GetOfficeResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedOfficeOutput | undefined;
};

/** @internal */
export const GetOfficeRequest$inboundSchema: z.ZodType<GetOfficeRequest, z.ZodTypeDef, unknown> = z
    .object({
        id: z.string(),
        remote_data: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remote_data: "remoteData",
        });
    });

/** @internal */
export type GetOfficeRequest$Outbound = {
    id: string;
    remote_data?: boolean | undefined;
};

/** @internal */
export const GetOfficeRequest$outboundSchema: z.ZodType<
    GetOfficeRequest$Outbound,
    z.ZodTypeDef,
    GetOfficeRequest
> = z
    .object({
        id: z.string(),
        remoteData: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOfficeRequest$ {
    /** @deprecated use `GetOfficeRequest$inboundSchema` instead. */
    export const inboundSchema = GetOfficeRequest$inboundSchema;
    /** @deprecated use `GetOfficeRequest$outboundSchema` instead. */
    export const outboundSchema = GetOfficeRequest$outboundSchema;
    /** @deprecated use `GetOfficeRequest$Outbound` instead. */
    export type Outbound = GetOfficeRequest$Outbound;
}

/** @internal */
export const GetOfficeResponseBody$inboundSchema: z.ZodType<
    GetOfficeResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedOfficeOutput$inboundSchema.optional(),
});

/** @internal */
export type GetOfficeResponseBody$Outbound = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedOfficeOutput$Outbound | undefined;
};

/** @internal */
export const GetOfficeResponseBody$outboundSchema: z.ZodType<
    GetOfficeResponseBody$Outbound,
    z.ZodTypeDef,
    GetOfficeResponseBody
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedOfficeOutput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOfficeResponseBody$ {
    /** @deprecated use `GetOfficeResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetOfficeResponseBody$inboundSchema;
    /** @deprecated use `GetOfficeResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetOfficeResponseBody$outboundSchema;
    /** @deprecated use `GetOfficeResponseBody$Outbound` instead. */
    export type Outbound = GetOfficeResponseBody$Outbound;
}
