/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetPurchaseOrderRequest = {
    /**
     * id of the purchaseorder you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Accounting software.
     */
    remoteData?: boolean | undefined;
};

export type GetPurchaseOrderResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedPurchaseOrderOutput | undefined;
};

/** @internal */
export const GetPurchaseOrderRequest$inboundSchema: z.ZodType<
    GetPurchaseOrderRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        remote_data: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remote_data: "remoteData",
        });
    });

/** @internal */
export type GetPurchaseOrderRequest$Outbound = {
    id: string;
    remote_data?: boolean | undefined;
};

/** @internal */
export const GetPurchaseOrderRequest$outboundSchema: z.ZodType<
    GetPurchaseOrderRequest$Outbound,
    z.ZodTypeDef,
    GetPurchaseOrderRequest
> = z
    .object({
        id: z.string(),
        remoteData: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPurchaseOrderRequest$ {
    /** @deprecated use `GetPurchaseOrderRequest$inboundSchema` instead. */
    export const inboundSchema = GetPurchaseOrderRequest$inboundSchema;
    /** @deprecated use `GetPurchaseOrderRequest$outboundSchema` instead. */
    export const outboundSchema = GetPurchaseOrderRequest$outboundSchema;
    /** @deprecated use `GetPurchaseOrderRequest$Outbound` instead. */
    export type Outbound = GetPurchaseOrderRequest$Outbound;
}

/** @internal */
export const GetPurchaseOrderResponseBody$inboundSchema: z.ZodType<
    GetPurchaseOrderResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedPurchaseOrderOutput$inboundSchema.optional(),
});

/** @internal */
export type GetPurchaseOrderResponseBody$Outbound = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedPurchaseOrderOutput$Outbound | undefined;
};

/** @internal */
export const GetPurchaseOrderResponseBody$outboundSchema: z.ZodType<
    GetPurchaseOrderResponseBody$Outbound,
    z.ZodTypeDef,
    GetPurchaseOrderResponseBody
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedPurchaseOrderOutput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPurchaseOrderResponseBody$ {
    /** @deprecated use `GetPurchaseOrderResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetPurchaseOrderResponseBody$inboundSchema;
    /** @deprecated use `GetPurchaseOrderResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetPurchaseOrderResponseBody$outboundSchema;
    /** @deprecated use `GetPurchaseOrderResponseBody$Outbound` instead. */
    export type Outbound = GetPurchaseOrderResponseBody$Outbound;
}
