/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetScoreCardRequest = {
    /**
     * id of the scorecard you want to retrieve.
     */
    id: string;
    /**
     * Set to true to include data from the original Ats software.
     */
    remoteData?: boolean | undefined;
};

export type GetScoreCardResponseBody = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedScoreCardOutput | undefined;
};

/** @internal */
export const GetScoreCardRequest$inboundSchema: z.ZodType<
    GetScoreCardRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        id: z.string(),
        remote_data: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remote_data: "remoteData",
        });
    });

/** @internal */
export type GetScoreCardRequest$Outbound = {
    id: string;
    remote_data?: boolean | undefined;
};

/** @internal */
export const GetScoreCardRequest$outboundSchema: z.ZodType<
    GetScoreCardRequest$Outbound,
    z.ZodTypeDef,
    GetScoreCardRequest
> = z
    .object({
        id: z.string(),
        remoteData: z.boolean().optional(),
    })
    .transform((v) => {
        return remap$(v, {
            remoteData: "remote_data",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetScoreCardRequest$ {
    /** @deprecated use `GetScoreCardRequest$inboundSchema` instead. */
    export const inboundSchema = GetScoreCardRequest$inboundSchema;
    /** @deprecated use `GetScoreCardRequest$outboundSchema` instead. */
    export const outboundSchema = GetScoreCardRequest$outboundSchema;
    /** @deprecated use `GetScoreCardRequest$Outbound` instead. */
    export type Outbound = GetScoreCardRequest$Outbound;
}

/** @internal */
export const GetScoreCardResponseBody$inboundSchema: z.ZodType<
    GetScoreCardResponseBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedScoreCardOutput$inboundSchema.optional(),
});

/** @internal */
export type GetScoreCardResponseBody$Outbound = {
    message?: string | undefined;
    error?: string | undefined;
    statusCode: number;
    data?: components.UnifiedScoreCardOutput$Outbound | undefined;
};

/** @internal */
export const GetScoreCardResponseBody$outboundSchema: z.ZodType<
    GetScoreCardResponseBody$Outbound,
    z.ZodTypeDef,
    GetScoreCardResponseBody
> = z.object({
    message: z.string().optional(),
    error: z.string().optional(),
    statusCode: z.number(),
    data: components.UnifiedScoreCardOutput$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetScoreCardResponseBody$ {
    /** @deprecated use `GetScoreCardResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetScoreCardResponseBody$inboundSchema;
    /** @deprecated use `GetScoreCardResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetScoreCardResponseBody$outboundSchema;
    /** @deprecated use `GetScoreCardResponseBody$Outbound` instead. */
    export type Outbound = GetScoreCardResponseBody$Outbound;
}
