/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type UpdateManagedWebhooksStatusRequest = {
    idConnection: string;
};

/** @internal */
export namespace UpdateManagedWebhooksStatusRequest$ {
    export const inboundSchema: z.ZodType<
        UpdateManagedWebhooksStatusRequest,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            id_connection: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                id_connection: "idConnection",
            });
        });

    export type Outbound = {
        id_connection: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        UpdateManagedWebhooksStatusRequest
    > = z
        .object({
            idConnection: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                idConnection: "id_connection",
            });
        });
}
