export const scopes = [
    'crm.contact.created',
    'crm.contact.pulled',
    'crm.company.created',
    'crm.company.pulled',
    'crm.deal.created',
    'crm.deal.pulled',
    'crm.engagement.created',
    'crm.engagement.pulled',
    'crm.note.created',
    'crm.note.pulled',
    'crm.stage.pulled',
    'crm.task.pulled',
    'crm.task.created',
    'crm.user.pulled',
    'ticketing.ticket.created',
    'ticketing.ticket.pulled',
    'ticketing.comment.created',
    'ticketing.comment.pulled',
    'ticketing.attachment.created',
    'ticketing.attachment.pulled',
    'ticketing.collection.pulled',
    'ticketing.account.pulled',
    'ticketing.contact.pulled',
    'ticketing.tag.pulled',
    'ticketing.team.pulled',
    'ticketing.user.pulled',

    'ats.activity.created',
    'ats.activity.pulled',
    'ats.application.created',
    'ats.application.pulled',
    'ats.attachment.created',
    'ats.attachment.pulled',
    'ats.candidate.created',
    'ats.candidate.pulled',
    'ats.department.pulled',
    'ats.eecos.pulled',
    'ats.interview.created',
    'ats.interview.pulled',
    'ats.job.pulled',
    'ats.jobinterviewstage.pulled',
    'ats.offer.created',
    'ats.office.pulled',
    'ats.rejectreason.pulled',
    'ats.scorecard.pulled',
    'ats.tag.pulled',
    'ats.user.pulled',

    'filestorage.file.created',
    'filestorage.file.pulled',
    'filestorage.folder.created',
    'filestorage.folder.pulled',
    'filestorage.group.pulled',
    'filestorage.user.pulled',
    'filestorage.drive.pulled',
    'filestorage.permission.pulled',
    'filestorage.sharedlink.pulled',

    'connection.created'
];

export enum WebhookScopes {
    'crm.contact.created' = 'crm.contact.created',
    'crm.contact.pulled' = 'crm.contact.pulled',
    'crm.company.created' = 'crm.company.created',
    'crm.company.pulled' = 'crm.company.pulled',
    'crm.deal.created' = 'crm.deal.created',
    'crm.deal.pulled' = 'crm.deal.pulled',
    'crm.engagement.created' = 'crm.engagement.created',
    'crm.engagement.pulled' = 'crm.engagement.pulled',
    'crm.note.created' = 'crm.note.created',
    'crm.note.pulled' = 'crm.note.pulled',
    'crm.stage.pulled' = 'crm.stage.pulled',
    'crm.task.pulled' = 'crm.task.pulled',
    'crm.task.created' = 'crm.task.created',
    'crm.user.pulled' = 'crm.user.pulled',

    'ticketing.ticket.created' = 'ticketing.ticket.created',
    'ticketing.ticket.pulled' = 'ticketing.ticket.pulled',
    'ticketing.comment.created' = 'ticketing.comment.created',
    'ticketing.comment.pulled' = 'ticketing.comment.pulled',
    'ticketing.attachment.created' = 'ticketing.attachment.created',
    'ticketing.attachment.pulled' = 'ticketing.attachment.pulled',
    'ticketing.collection.pulled' = 'ticketing.collection.pulled',
    'ticketing.account.pulled' = 'ticketing.account.pulled',
    'ticketing.contact.pulled' = 'ticketing.contact.pulled',
    'ticketing.tag.pulled' = 'ticketing.tag.pulled',
    'ticketing.team.pulled' = 'ticketing.team.pulled',
    'ticketing.user.pulled' = 'ticketing.user.pulled',

    'ats.activity.created' = 'ats.activity.created',
    'ats.activity.pulled' = 'ats.activity.pulled',
    'ats.application.created' = 'ats.application.created',
    'ats.application.pulled' = 'ats.application.pulled',
    'ats.attachment.created' = 'ats.attachment.created',
    'ats.attachment.pulled' = 'ats.attachment.pulled',
    'ats.candidate.created' = 'ats.candidate.created',
    'ats.candidate.pulled' = 'ats.candidate.pulled',
    'ats.department.pulled' = 'ats.department.pulled',
    'ats.eecos.pulled' = 'ats.eecos.pulled',
    'ats.interview.created' = 'ats.interview.created',
    'ats.interview.pulled' = 'ats.interview.pulled',
    'ats.job.pulled' = 'ats.job.pulled',
    'ats.jobinterviewstage.pulled' = 'ats.jobinterviewstage.pulled',
    'ats.offer.created' = 'ats.offer.created',
    'ats.office.pulled' = 'ats.office.pulled',
    'ats.rejectreason.pulled' = 'ats.rejectreason.pulled',
    'ats.scorecard.pulled' = 'ats.scorecard.pulled',
    'ats.tag.pulled' = 'ats.tag.pulled',
    'ats.user.pulled' = 'ats.user.pulled',

    'filestorage.file.created'= 'filestorage.file.created',
    'filestorage.file.pulled' = 'filestorage.file.pulled',
    'filestorage.folder.created' = 'filestorage.folder.created',
    'filestorage.folder.pulled' = 'filestorage.folder.pulled',
    'filestorage.group.pulled' = 'filestorage.group.pulled',
    'filestorage.user.pulled' = 'filestorage.user.pulled',
    'filestorage.drive.pulled' = 'filestorage.drive.pulled',
    'filestorage.permission.pulled' = 'filestorage.permission.pulled',
    'filestorage.sharedlink.pulled' = 'filestorage.sharedlink.pulled',

    'connection.created' = 'connection.created'
}
