# run directly from the repo root directory
# docker build -f ./apps/client-ts/Dockerfile.dev .
FROM node:20-alpine AS base
# =======================================================================
FROM base AS builder
RUN apk add --no-cache libc6-compat
RUN apk update

# Set pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

ARG VITE_BACKEND_DOMAIN
ARG VITE_FRONTEND_DOMAIN
ARG VITE_STYTCH_TOKEN

ENV VITE_BACKEND_DOMAIN="$VITE_BACKEND_DOMAIN"
ENV VITE_FRONTEND_DOMAIN="$VITE_FRONTEND_DOMAIN"
ENV VITE_STYTCH_TOKEN="$VITE_STYTCH_TOKEN"

RUN corepack enable

WORKDIR /app
RUN pnpm add -g turbo@1.13.4

# Start the Webapp
CMD cd apps/client-ts && pnpm install && pnpm run dev
