/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateConnectionStrategyDto = {
    type: string;
    attributes: Array<string>;
    values: Array<string>;
};

/** @internal */
export namespace CreateConnectionStrategyDto$ {
    export const inboundSchema: z.ZodType<CreateConnectionStrategyDto, z.ZodTypeDef, unknown> =
        z.object({
            type: z.string(),
            attributes: z.array(z.string()),
            values: z.array(z.string()),
        });

    export type Outbound = {
        type: string;
        attributes: Array<string>;
        values: Array<string>;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateConnectionStrategyDto> =
        z.object({
            type: z.string(),
            attributes: z.array(z.string()),
            values: z.array(z.string()),
        });
}
