/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedPayrollRunOutput = {};

/** @internal */
export namespace UnifiedPayrollRunOutput$ {
    export const inboundSchema: z.ZodType<UnifiedPayrollRunOutput, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UnifiedPayrollRunOutput> =
        z.object({});
}
