/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedJobOutput = {};

/** @internal */
export namespace UnifiedJobOutput$ {
    export const inboundSchema: z.ZodType<UnifiedJobOutput, z.ZodTypeDef, unknown> = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UnifiedJobOutput> = z.object({});
}
