/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedCampaignInput = {};

/** @internal */
export const UnifiedCampaignInput$inboundSchema: z.ZodType<
    UnifiedCampaignInput,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UnifiedCampaignInput$Outbound = {};

/** @internal */
export const UnifiedCampaignInput$outboundSchema: z.ZodType<
    UnifiedCampaignInput$Outbound,
    z.ZodTypeDef,
    UnifiedCampaignInput
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedCampaignInput$ {
    /** @deprecated use `UnifiedCampaignInput$inboundSchema` instead. */
    export const inboundSchema = UnifiedCampaignInput$inboundSchema;
    /** @deprecated use `UnifiedCampaignInput$outboundSchema` instead. */
    export const outboundSchema = UnifiedCampaignInput$outboundSchema;
    /** @deprecated use `UnifiedCampaignInput$Outbound` instead. */
    export type Outbound = UnifiedCampaignInput$Outbound;
}
