/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedCompanyOutput = {};

/** @internal */
export const UnifiedCompanyOutput$inboundSchema: z.ZodType<
    UnifiedCompanyOutput,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UnifiedCompanyOutput$Outbound = {};

/** @internal */
export const UnifiedCompanyOutput$outboundSchema: z.ZodType<
    UnifiedCompanyOutput$Outbound,
    z.ZodTypeDef,
    UnifiedCompanyOutput
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedCompanyOutput$ {
    /** @deprecated use `UnifiedCompanyOutput$inboundSchema` instead. */
    export const inboundSchema = UnifiedCompanyOutput$inboundSchema;
    /** @deprecated use `UnifiedCompanyOutput$outboundSchema` instead. */
    export const outboundSchema = UnifiedCompanyOutput$outboundSchema;
    /** @deprecated use `UnifiedCompanyOutput$Outbound` instead. */
    export type Outbound = UnifiedCompanyOutput$Outbound;
}
