/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedEeocsOutput = {};

/** @internal */
export namespace UnifiedEeocsOutput$ {
    export const inboundSchema: z.ZodType<UnifiedEeocsOutput, z.ZodTypeDef, unknown> = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UnifiedEeocsOutput> = z.object(
        {}
    );
}
