/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedDependentOutput = {};

/** @internal */
export namespace UnifiedDependentOutput$ {
    export const inboundSchema: z.ZodType<UnifiedDependentOutput, z.ZodTypeDef, unknown> = z.object(
        {}
    );

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UnifiedDependentOutput> =
        z.object({});
}
