/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedDependentInput = {};

/** @internal */
export const UnifiedDependentInput$inboundSchema: z.ZodType<
    UnifiedDependentInput,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UnifiedDependentInput$Outbound = {};

/** @internal */
export const UnifiedDependentInput$outboundSchema: z.ZodType<
    UnifiedDependentInput$Outbound,
    z.ZodTypeDef,
    UnifiedDependentInput
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedDependentInput$ {
    /** @deprecated use `UnifiedDependentInput$inboundSchema` instead. */
    export const inboundSchema = UnifiedDependentInput$inboundSchema;
    /** @deprecated use `UnifiedDependentInput$outboundSchema` instead. */
    export const outboundSchema = UnifiedDependentInput$outboundSchema;
    /** @deprecated use `UnifiedDependentInput$Outbound` instead. */
    export type Outbound = UnifiedDependentInput$Outbound;
}
