/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedAccountOutput = {};

/** @internal */
export namespace UnifiedAccountOutput$ {
    export const inboundSchema: z.ZodType<UnifiedAccountOutput, z.ZodTypeDef, unknown> = z.object(
        {}
    );

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UnifiedAccountOutput> = z.object(
        {}
    );
}
