/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedPayGroupInput = {};

/** @internal */
export const UnifiedPayGroupInput$inboundSchema: z.ZodType<
    UnifiedPayGroupInput,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type UnifiedPayGroupInput$Outbound = {};

/** @internal */
export const UnifiedPayGroupInput$outboundSchema: z.ZodType<
    UnifiedPayGroupInput$Outbound,
    z.ZodTypeDef,
    UnifiedPayGroupInput
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnifiedPayGroupInput$ {
    /** @deprecated use `UnifiedPayGroupInput$inboundSchema` instead. */
    export const inboundSchema = UnifiedPayGroupInput$inboundSchema;
    /** @deprecated use `UnifiedPayGroupInput$outboundSchema` instead. */
    export const outboundSchema = UnifiedPayGroupInput$outboundSchema;
    /** @deprecated use `UnifiedPayGroupInput$Outbound` instead. */
    export type Outbound = UnifiedPayGroupInput$Outbound;
}
