/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedScreeningQuestionOutput = {};

/** @internal */
export namespace UnifiedScreeningQuestionOutput$ {
    export const inboundSchema: z.ZodType<UnifiedScreeningQuestionOutput, z.ZodTypeDef, unknown> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UnifiedScreeningQuestionOutput> =
        z.object({});
}
