/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type UnifiedPayGroupOutput = {};

/** @internal */
export namespace UnifiedPayGroupOutput$ {
    export const inboundSchema: z.ZodType<UnifiedPayGroupOutput, z.ZodTypeDef, unknown> = z.object(
        {}
    );

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UnifiedPayGroupOutput> =
        z.object({});
}
